### ISSUE TITLE
Fix random undefined for second player ID on joining

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#110]
@Masclins can you detail your issue here? I think it mostly works for me locally, but I'll put any problems I find here as well.

**Comment by kenan-rhoton** [comment]
For me, my only issue is sometimes, randomly, upon joining the game as the second player, the playerid will come up as `undefined` and there's no way to retrieve the "correct" value, effectively stopping the game from being able to start.

I will look into this.

**Comment by Masclins** [comment]
I works now :confused:

**Comment by kenan-rhoton** [comment]
Reopening due to there still being a problem with the player IDs as stated, changed title to reflect this

**Comment by Masclins** [comment]
I'd been making a lot of games this week and never encountered this error.

I found, though, an error when you played a card by clicking on a card you own (trying to click its row). It's solved by #115

**Comment by Masclins** [comment]
This Issue was opened for a bug that only happened once to me (maybe was some connection problem).
Then was reopened for some bug that could not be replicated.

I think this is the least efficient way to handle bug issues.

IMHO this Issue should be closed and we should write a guide on how to create Issues, specially those bug-related. (And it should probably be part of #123)

**Comment by kenan-rhoton** [comment]
Agreed
