### ISSUE TITLE
Clarify game board

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#15]
Change the play-card behavior so that it more clearly delimits which card is who's instead of the very ugly "Owner" tag.

One options is to divide the play area into TWO areas (my-area and opponent-area) and make cards go there. Bonus points for symmetry.

**Comment by kenan-rhoton** [comment]
I would like to clarify that this is a `frontend` issue, the backend already hands out the correct info

**Comment by Masclins** [comment]
I like the idea of two areas.
`:rows` would be `[[[][][][][]][[][][][][]]]` instead of current `[[][][][][]]`. First index for player 0, second for 1.
`:next-play` will be change accordingly, since now indexes 0 and 1 mean nothing and they would give info regarding whose play it is. By making them `nil` after calling `apply-all-plays` we won't need `:play-wanted` anymore.

**Comment by kenan-rhoton** [comment]
Actually, I was thinking about this as a frontend-only issue, but if you want to make changes to backend **at the same time** as frontend to clarify it further, then go for it!

**Comment by Masclins** [comment]
I think it has more sense to first address Issue #13

**Comment by kenan-rhoton** [comment]
I agree, hence why this issue isn't tagged as necessary for the release 🙃
