### ISSUE TITLE
Scores in frontend

### ISSUE THREAD

**Issue by kenan-rhoton** [kenan-rhoton/card-game#18]
Make the scores in frontend actually mean something. Right now `my-score` and `opponent-score` do **absolutely nothing** in frontend/src/components/Game.vue

**Comment by ruchnar** [comment]
It's very unlikely for me to have this "soon". Anyway, we should change the way it's coded (and add a function) in order to properly show the scores.  

Unless I'm wrong, the code provides the total amount of points in each row for each player with a function. And the player who has more points at that point with another function.
So we need to add another function in between, in order to check the total points (rows won) for each player (2 outputs). 
This will involve changing also how the second function works (we can reuse the new function in this one).


Ara mateix només es compara els valors i retorna quin jugador té més punts, per tant aquesta funció no serveix per al que es vol fer.

**Comment by Masclins** [comment]
If you feel like a function is needed to do so, either do it or create an issue to do it (and do the review when it's done, so you understand how it works)
